---
name: Business::Bof::Server
version: 0.06
author:
  - Kaare Rasmussen <kar at kakidata.dk>
abstract: Application Server featuring User Control and Remote Object Execution
license: perl
requires:
  Class::DBI: x
  DBD::SQLite: 0
  DBIx::Recordset: 0
  DateTime: 0.22
  Digest::MD5: 2.33
  LWP::Protocol::https: 0
  Log::Log4perl: 0.47
  POE: 0.29
  POE::Component::Server::SOAP: 1.05
  Printer: 0
  XML::Dumper: 0.71
provides:
  Business::Bof::Data::Fw:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Data::Fw::fw_database:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Data::Fw::fw_menu:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Data::Fw::fw_menulink:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Data::Fw::fw_schedule:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Data::Fw::fw_task:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Data::Fw::fw_taskresult:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Data::Fw::fw_user:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Data::Fw::fw_usergroup:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Data::Fw::fw_useringroup:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Data::Fw::fw_usermenu:
    file: lib/Business/Bof/Data/Fw.pm
  Business::Bof::Server:
    file: lib/Business/Bof/Server.pm
  Business::Bof::Server::CLI:
    file: lib/Business/Bof/Server/CLI.pm
    version: 0.05
  Business::Bof::Server::Connection:
    file: lib/Business/Bof/Server/Connection.pm
    version: 0.05
  Business::Bof::Server::Docprint:
    file: lib/Business/Bof/Server/Docprint.pm
    version: 0.05
  Business::Bof::Server::Fw:
    file: lib/Business/Bof/Server/Fw.pm
    version: 0.05
  Business::Bof::Server::Schedule:
    file: lib/Business/Bof/Server/Schedule.pm
    version: 0.05
  Business::Bof::Server::Session:
    file: lib/Business/Bof/Server/Session.pm
    version: 0.05
  Business::Bof::Server::Task:
    file: lib/Business/Bof/Server/Task.pm
    version: 0.05
generated_by: Module::Build version 0.261
